name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board: ["BOARD_CREALITY_V4", "BOARD_CREALITY_V427"]
        grid: [3,5,7]
    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: backup config
      run: |
        mkdir backup
        cp Marlin/Configuration.h backup/Configuration.h
        cp Marlin/Configuration_adv.h backup/Configuration_adv.h
    - name: Copy BlTouch Configs
      run: |
        cp Configuration\ Files/E3V2\ Templates/$CONFIG/Configuration.h Marlin/Configuration.h
        cp Configuration\ Files/E3V2\ Templates/$CONFIG/Configuration_adv.h Marlin/Configuration_adv.h
      env:
        CONFIG: BLTouch-3x3
    - name: Run PlatformIO BL-Touch
      run: |
        pio run -e STM32F103RET6_creality
        mv .pio/build/STM32F103RET6_creality/*.bin Precompiled\ Firmware/E3V2-$CONFIG-$BOARD-$GRID.bin
      env:
        CONFIG: BLTouch-3x3
        BOARD: ${{ matrix.board }}
        GRID: ${{ matrix.grid }}
    - name: Restore original config
      run: |
        mv backup/Configuration.h Marlin/Configuration.h 
        mv backup/Configuration_adv.h Marlin/Configuration_adv.h
        rmdir backup
    - name: Commit new builds
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'github.actions@users.noreply.github.com'
        git add .
        git commit -am "New Precompiled Firmware"
        git push